### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by RuthSalvador** [omairapalacios/LIM011-fe-social-network#1]
Objetivos pendientes:

- Uso de callbacks: como me comentaste estás empezando a sentirte más segura en este tema, recuerda seguir practicándolo. 
- Testeo asíncrono
- Labels (github)
- Local Storage: como conversamos te sugiero que lo puedas practicar en tus ratos libres, siempre es útil [recurso](https://lms.laboratoria.la/cohorts/lim-2019-05-bc-core-lim010/courses/browser/03-browser-apis/03-web-storage)

**Comment by omairapalacios** [comment]
Gracias Ruth ! :)
